Repository tower-rs/tower, pull requests merged in 2024-07, with the labels that each got.

#733 chore: Remove unmatched deny ignore config
  deny.toml
Labels: C-cleanup, T-ci

#755 remove generic parameters from Reconnect::new
  tower/src/reconnect/mod.rs
Labels: A-reconnect, C-cleanup

#741 Upgrade to indexmap v2 (MSRV 1.63)
  .github/workflows/CI.yml
  README.md
  tower/Cargo.toml
  tower/README.md
  tower/src/lib.rs
  tower/src/ready_cache/cache.rs
Labels: A-ready-cache, C-cleanup, relnotes

#754 ensure that re-exported symbols show feature label in root
  tower/src/lib.rs
Labels: C-enhancement, T-docs, A-make, A-util

#760 feat: Make new functions const when possible
  tower-layer/src/identity.rs
  tower-layer/src/stack.rs
  tower-service/src/lib.rs
  tower/src/balance/p2c/layer.rs
  tower/src/balance/p2c/make.rs
  tower/src/buffer/layer.rs
  tower/src/builder/mod.rs
  tower/src/filter/layer.rs
  tower/src/filter/mod.rs
  tower/src/hedge/delay.rs
  tower/src/hedge/latency.rs
  tower/src/hedge/select.rs
  tower/src/limit/concurrency/layer.rs
  tower/src/limit/rate/layer.rs
  tower/src/limit/rate/rate.rs
  tower/src/load/completion.rs
  tower/src/load/constant.rs
  tower/src/load/pending_requests.rs
  tower/src/load_shed/error.rs
  tower/src/load_shed/layer.rs
  tower/src/load_shed/mod.rs
  tower/src/make/make_service/shared.rs
  tower/src/reconnect/mod.rs
  tower/src/retry/layer.rs
  tower/src/retry/mod.rs
  tower/src/spawn_ready/service.rs
  tower/src/timeout/error.rs
  tower/src/timeout/layer.rs
  tower/src/timeout/mod.rs
  tower/src/util/and_then.rs
  tower/src/util/call_all/common.rs
  tower/src/util/future_service.rs
  tower/src/util/map_err.rs
  tower/src/util/map_future.rs
  tower/src/util/map_request.rs
  tower/src/util/map_response.rs
  tower/src/util/map_result.rs
  tower/src/util/oneshot.rs
  tower/src/util/optional/mod.rs
  tower/src/util/ready.rs
  tower/src/util/then.rs
Labels: C-enhancement, S-blocked

#775 chore: fix spelling errors
  guides/building-a-middleware-from-scratch.md
  tower/src/balance/p2c/mod.rs
  tower/src/ready_cache/cache.rs
  tower/src/steer/mod.rs
  tower/src/util/call_all/ordered.rs
  tower/src/util/rng.rs
Labels: T-docs, C-cleanup

#740 chore: update GitHub Actions CI
  .github/workflows/CI.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: C-cleanup, T-ci

#779 fix warnings found when running check/doc commands
  examples/Cargo.toml
  tower-service/Cargo.toml
  tower/Cargo.toml
  tower/src/lib.rs
  tower/src/load/pending_requests.rs
  tower/src/util/call_all/ordered.rs
  tower/src/util/rng.rs
Labels: C-cleanup

#780 chore: fix a few typos
  tower/src/builder/mod.rs
  tower/src/load/mod.rs
  tower/src/ready_cache/cache.rs
  tower/src/util/call_all/common.rs
Labels: C-cleanup, S-waiting-on-author
